### ISSUE TITLE
App is not open source, so please change LICENSE file in this github repo

### ISSUE THREAD

**Issue by pizzadude** [keshavbhatt/plumber#1]
App is not open source, so please change LICENSE file in this github repo

**Comment by keshavbhatt** [comment]
this github repo i set for CI purpose, since there is no code in the repo, the license set here doesn't represent the license of app's source code. A Github repo is not just used to host source code of software, its not a store front. snapcraft.io/plumber is, i set the app license there already.
If you satisfied with the answer please close this.

**Comment by pizzadude** [comment]
Ok.
